export const scaleFactor = 4;

export const dialogueData = {
  industryPortfolio: `Since a few years ago, I tried to put all the knowledge of my different backgrounds together. The result of this is my Industrial IT Portfolio. 
  <br/><br/>Please have a look to it clicking this link <a href="https://industrial-it-portfolio.vercel.app/" target="_blank">Industrial Portfolio</a>.`,
  rpaPortfolio: `I've worked as a DPA and RPA developer in different companies for four years. In order to prove my knowledge of the different RPA and DPA tools I built this Portfolio.  
  <br/><br/>Please have a look to it clicking this link <a href="https://rpa-portfolio.vercel.app/" target="_blank">DPA/RPA Portfolio</a>.`,
  fullStackPortfolio: `I've worked as a software developer in different companies for two years. In order to prove my knowledge of the different Pro Code / Low Code technologies I build this Portfolio.  
  <br/><br/>Please have a look to it clicking this link <a href="https://full-stack-port-folio.vercel.app/" target="_blank">Full Stack Portfolio</a>.`,
  mlPortfolio: `I've been studying and improving my knowledge of Machine Learning since a few years ago. I finished some certificates in this field and I  experienced with prebuilt models in my last jobs. In order to prove my knowledge of the different Machine Learning technologies I build this Portfolio.  
  <br/><br/>Please have a look to it clicking this link <a href="https://ml-developer-portfolio.vercel.app/" target="_blank">Machine Learning Portfolio</a>.`,
  infoPoint: `Hello everybody!. My name is Manuel Portero Leiva and I'm a well educated Software developer and Industrial Engineer. I consider myself as an analytical, good problem solver and efficient professional.</br></br><Strong><u>Please walk around my home and check the different items</u></strong>.  <ul><li><strong>Go to the Tv (Point 0) </strong> and check my personal website.</li></br><li><strong>Go to the computers</strong> and check my different portfolios. <br/><br/>ML Developer <Strong>(Point 1)</Strong><br/><br/> Full Stack Developer <Strong>(Point 2)</Strong><br/><br/> RPA Developer <Strong>(Point 3)</Strong><br/><br/> Industrial IT <Strong>(Point 4)</Strong> </li></br><li><strong>Check the certificate</strong> and see my education.</li></br><li><strong>Go to the next room</strong> and check my degree's projects <Strong>(Point 6)</Strong> and my hobbies <Strong>(Points 5,7,8,9)</Strong>.</li></ul><br/> Every checked item will allow you to know me a little bit better :).`,
  education: `Please see below my education list. <br/><br/> <strong>Education</strong>: <br/><br/><strong>Ceu San Pablo:</strong> Master in health and safety <br/><br/> <strong>Universitat Autonoma de Barcelona:</strong> Bachelor with honours in Chemical Engineering <br/><br/><strong>Institut Obert de Catalunya:</strong> Computer Science <br/><br/><strong>Glasgow Kelvin College:</strong> HNC Web Development <br/><br/><strong>Barcelona Activa IT Academy:</strong> ML/Big data education`,
  sofa: `Do you want to watch the tv ? . I suggest you to check the multimedia content of my website then!. <br/><br/> Please click this link and check it out  :
   <a href="https://profesionalwebsite-mpl.vercel.app/" target="_blank">Manuel Portero Website</a>.<br/><br/>You can also check my linkedin and my resume : <br/><br/> Linkedin : <a href="https://www.linkedin.com/in/manuel-portero-leiva-50b429265/" target="_blank">Linkedin Link</a><br/><br/>Resume (English): <a href="https://www.dropbox.com/scl/fi/74hjhncukppnp30gvt2yv/MPLCVGenerico-English.pdf?rlkey=ys8f4uzl9mj00en2g10lr5rw4&dl=0" target="_blank">Cv (English version)</a><br/><br/>Resume (Spanish): <a href="https://www.dropbox.com/scl/fi/zx3tp1tlfdbxnw84qyig9/MPLCVGenerico-Espa-ol.pdf?rlkey=frtj153oajqb4avwk1wt7z2k8&dl=0" target="_blank">Cv (Spanish version)</a>`, 
  printer: `I use to make projects with my 3D printer and my Arduino devices (MycroPython) in my free time. I'm planning to create a portfolio soon but it's not ready yet ^^'`, 
  tv: `Do you want to watch the tv ? . I suggest you to check the multimedia content of my website then!. <br/><br/> Please click this link and check it out  :
   <a href="https://profesionalwebsite-mpl.vercel.app/" target="_blank">Manuel Portero Website</a>.<br/><br/>You can also check my linkedin and my resume : <br/><br/> Linkedin : <a href="https://www.linkedin.com/in/manuel-portero-leiva-50b429265/" target="_blank">Linkedin Link</a><br/><br/>Resume (English): <a href="https://www.dropbox.com/scl/fi/74hjhncukppnp30gvt2yv/MPLCVGenerico-English.pdf?rlkey=ys8f4uzl9mj00en2g10lr5rw4&dl=0" target="_blank">Cv (English version)</a><br/><br/>Resume (Spanish): <a href="https://www.dropbox.com/scl/fi/zx3tp1tlfdbxnw84qyig9/MPLCVGenerico-Espa-ol.pdf?rlkey=frtj153oajqb4avwk1wt7z2k8&dl=0" target="_blank">Cv (Spanish version)</a>`,
  bed: `Im actually settled in Barcelona, but I've been living for 5 years in Glasgow (UK), due that I'm used to work with people from different cultures.</br></br>In order to prove this please check thee two reference letter from my living period in the UK : </br/></br> KPC Complex : <a href="https://www.dropbox.com/scl/fi/ylx2onabobrqdbp86w4lh/Manuel_ReferenceKPC.pdf?rlkey=wnbczb7yeimgtcc0p92wpeh2l&dl=0" target="_blank">KPC Reference</a></br/></br/> Repair Cafe : <a href="https://www.dropbox.com/scl/fi/efm5awtt1h3yplh6zt55a/Manuel_ReferenceRepairCafe.pdf?rlkey=db5fceshuq6wkgqufkirrge17&dl=0" target="_blank">R.Cafe Reference</a></br/>`,
  printer2: `I use to make projects with my 3D printer and my Arduino devices (MycroPython) in my free time. I'm planning to create a portfolio soon but it's not ready yet ^^'`, 
  projects: `Please see below degree's projects list. <br/><br/> <strong>Degree's projects</strong> : <br/><br/><strong>Master in Health and Safety :</strong> <a href="https://www.dropbox.com/scl/fi/br7v49r999mykm5zdb03f/PFM-papeleria-herederos-garcia.pdf?rlkey=u5xh9qk8vvovai68c7qlyx99p&dl=0" target="_blank">Libreria H.Garcia Auditory</a> <br/><br/> <strong>Bachelor with honours in Chemical Engineering:</strong> <a href="https://www.dropbox.com/scl/fi/t7ns75jccx7x7wgim8pjn/PFC_Caprojams_part01.pdf?rlkey=vywnhx0nkmyti3a7hwg6rh7xd&dl=0" target="_blank">Caprolactam's factory construction</a> <br/><br/><strong>Computer Science:</strong> <a href="https://www.dropbox.com/scl/fi/x7pnr93q9umdfm139r3y9/ASX_M14_TEA4_A_Hotel_Dreams_and_Feel.pdf?rlkey=680fk72e61dlj52ko40l52xu0&dl=0" target="_blank">Network system construction</a> <br/><br/><strong>HNC Web Development:</strong> <a href="https://www.youtube.com/watch?v=C8DJYeXkOcI" target="_blank">Social Network Development</a>  <br/><br/><strong>ML/Big Data Certificates:</strong> <a href="https://github.com/SteelTitansax/EnergyPredictionSolution" target="_blank">Energy Prediction Digital Solution</a>`,
  languages: `I use to learn and practice languages as a hobby.Please see below a list of y language skills. <br/><br/> <strong>Language Skills</strong>: <br/><br/><strong>Spanish:</strong> Native<br/><br/> <strong>English:</strong> Native<br/><br/><strong>Catalan:</strong> Native <br/><br/><strong>Italian:</strong> High<br/><br/><strong>French:</strong> Intermediate`,
  chair: 'Contact me If you like this game presentation. <br/><br/> <strong>Author</strong>: <br/><br/>Manuel Portero Leiva<br/><br/> <a href="https://profesionalwebsite-mpl.vercel.app/hireme" target="_blank">Contact details</a><br/><br/><strong>Best Regards</strong><br/>Manuel Portero Leiva',
  chair2: 'Please see below my work experience: <br/><br/> <a href="https://www.linkedin.com/in/manuel-portero-leiva-50b429265/" target="_blank">Work Experience history</a>',
  exit: `If you want to close this presentation game. Please close the browser tab.`,
};
