export const scaleFactor = 4;

export const dialogueData = {
  industryPortfolio: `Since a few years ago, I tried to put all the knowledge of my different backgrounds together. The result of this is my Industrial IT Portfolio. 
  <br/><br/>Please have a look to it clicking this link <a href="https://industrial-it-portfolio.vercel.app/" target="_blank">Industrial Portfolio</a>.`,
  rpaPortfolio: `I've worked as a DPA and RPA developer in different companies for four years. In order to prove my knowledge of the different RPA and DPA tools I built this Portfolio.  
  <br/><br/>Please have a look to it clicking this link <a href="https://rpa-portfolio.vercel.app/" target="_blank">DPA/RPA Portfolio</a>.`,
  fullStackPortfolio: `I've worked as a software developer in different companies for two years. In order to prove my knowledge of the different Pro Code / Low Code technologies I build this Portfolio.  
  <br/><br/>Please have a look to it clicking this link <a href="https://full-stack-port-folio.vercel.app/" target="_blank">Full Stack Portfolio</a>.`,
  mlPortfolio: `I've been studying and improving my knowledge of Machine Learning since a few years ago. I finished some certificates in this field and I  experienced with prebuilt models in my last jobs. In order to prove my knowledge of the different Machine Learning technologies I build this Portfolio.  
  <br/><br/>Please have a look to it clicking this link <a href="https://ml-developer-portfolio.vercel.app/" target="_blank">Machine Learning Portfolio</a>.`,
  infoPoint: `Hello everybody!. My name is Manuel Portero Leiva and I'm a well educated Software developer and Industrial Engineer. I consider myself as an analytical, good problem solver and efficient professional.</br></br><Strong><u>Please walk around my home and check the different items</u></strong>.  <ul><li><strong>Go to the Tv</strong> and check my personal website.</li></br><li><strong>Go to the computers</strong> and check my different portfolios.</li></br><li><strong>Check the certificate</strong> and see my education.</li></br><li><strong>Go to the next room</strong> and check my degree's projects (Library) and my hobbies.</li></ul><br/> Every checked item will allow you to know me a little bit better :).`,
  education: `Please see below my education list. <br/><br/> <strong>Education</strong>: <br/><br/><strong>Ceu San Pablo:</strong> Master in health and safety <br/><br/> <strong>Universitat Autonoma de Barcelona:</strong> Bachelor with honours in Chemical Engineering <br/><br/><strong>Institut Obert de Catalunya:</strong> Computer Science <br/><br/><strong>Glasgow Kelvin College:</strong> HNC Web Development <br/><br/><strong>Barcelona Activa IT Academy:</strong> ML/Big data education`,
  sofa: `Do you want to watch the tv ? . I suggest you to check my multimedia content in my website then!. <br/><br/> Please click this link and check it out  :
   <a href="https://profesionalwebsite-mpl.vercel.app/" target="_blank">Manuel Portero Website</a>.`,
  printer: `I use to make projects with my 3D printer and my Arduino devices (MycroPython) in my free time. I'm planning to create a portfolio soon but it's not ready yet ^^'`, 
  tv: `Do you want to watch the tv ? . I suggest you to check the multimedia content of my website then!. <br/><br/> Please click this link and check it out  :
   <a href="https://profesionalwebsite-mpl.vercel.app/" target="_blank">Manuel Portero Website</a>.`, 
  bed: `Im actually settled in Barcelona, but I've been living for 5 years in Glasgow (UK), due that I'm used to work with people from different cultures.`,
  bed2: `Im actually stettled in Barcelona, but I've been living for 5 years in Glasgow (UK), due that I'm used to work with people from different cultures.`,
  projects: `Please see below degree's projects list. <br/><br/> <strong>Degree's projects</strong> : <br/><br/><strong>Master in Health and Safety :</strong> <a href="https://www.dropbox.com/sh/to5o9owoelv300d/AADpnXG5E0edLunAg5iJc016a?dl=0" target="_blank">Libreria H.Garcia Auditory</a> <br/><br/> <strong>Bachelor with honours in Chemical Engineering:</strong> <a href="https://www.dropbox.com/sh/0hphyx8llr9bvu7/AAArof83CAi9Awe9PvemWEGca?dl=0" target="_blank">Caprolactam's factory construction</a> <br/><br/><strong>Computer Science:</strong> <a href="https://www.dropbox.com/login?cont=%2Fhome%2FTFG_Sys_admin" target="_blank">Network system construction</a> <br/><br/><strong>HNC Web Development:</strong> <a href="https://www.dropbox.com/login?cont=%2Fhome%2FPFG_Web_Development" target="_blank">Social Network Development</a>`,
  languages: `I use to learn and practice languages as a hobby.Please see below a list of y language skills. <br/><br/> <strong>Language Skills</strong>: <br/><br/><strong>Spanish:</strong> Native<br/><br/> <strong>English:</strong> Native<br/><br/><strong>Catalan:</strong> Native <br/><br/><strong>Italian:</strong> High<br/><br/><strong>French:</strong> Intermediate`,
  chair: 'Contact me If you like this game presentation. <br/><br/> <strong>Author</strong>: <br/><br/>Manuel Portero Leiva<br/><br/> <a href="https://profesionalwebsite-mpl.vercel.app/hireme" target="_blank">Contact details</a><br/><br/><strong>Best Regards</strong><br/>Manuel Portero Leiva',
  chair2: 'Contact me If you like this game presentation. <br/><br/> <strong>Author</strong>: <br/><br/>Manuel Portero Leiva<br/><br/> <a href="https://profesionalwebsite-mpl.vercel.app/hireme" target="_blank">Contact details</a><br/><br/><strong>Best Regards</strong><br/>Manuel Portero Leiva',
  exit: `If you want to close this presentation game. Please close the browser tab.`,
};
